import type { Metadata } from "next";
import { Inter, Comfortaa, Roboto_Flex } from "next/font/google";
import "./globals.css";
import { Navbar } from "./components/Navbar";

const inter = Roboto_Flex({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Apeteat",
  description: "Generated by CRLS",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <Navbar />
        </div>
        {children}
        <h1>Footer</h1>
      </body>
    </html>
  );
}
